### ISSUE TITLE
open-pip requires node > 7.6.0 for async

### ISSUE THREAD

**Issue by edm00se** [albinekb/open-pip#1]
I just installed [open-pip-cli](https://github.com/albinekb/open-pip-cli) latest (looks like 1.2.1), which uses `open-pip` 3.0.5. To make a long story short, I believe that the real issue here is that async functions are not supported in Node <7.6.0 (such as LTS 6.x, in my case 6.10.1); per [node.green](http://node.green/#ES2017-features-async-functions).

<details><summary>error to console</summary><p>

```
λ ~ → open-pip --help
/Users/<myUserAccount>/.nvm/versions/node/v6.10.1/lib/node_modules/open-pip-cli/node_modules/open-pip/index.js:7
const parseUrl = async (string) => {
                       ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/barnacles/.nvm/versions/node/v6.10.1/lib/node_modules/open-pip-cli/index.js:2:14)
```
</p></details>

**Comment by edm00se** [comment]
Alternatively, the library could be modified to create the dist version using babel, allowing for older versions of node to work.

**Comment by albinekb** [comment]
Yeah i can rewrite it tonight using just .then instead of async/await if you want to use it in old node if you want :)

It's just a matter of adding https://github.com/leebyron/async-to-gen

**Comment by edm00se** [comment]
I tend to stick to the latest LTS release, so it's preferable to me. 😆

**Comment by albinekb** [comment]
Closing, if you want you can open a PR to change this 😄 node 8 is soon LTS 👌

**Comment by edm00se** [comment]
Now we just need to wait for [October 1st](https://github.com/nodejs/LTS#lts-schedule1).
